---

# Create EDA Controller Rulebook Activations
- name: Add EDA Controller rulebook activation
  rulebook_activation:
    name:             "{{ __activation_item.name }}"
    new_name:         "{{ __activation_item.new_name | default(omit) }}"
    description:      "{{ __activation_item.description | default(omit) }}"
    project:          "{{ __activation_item.project | default(omit) }}"
    rulebook:         "{{ __activation_item.rulebook | default(omit) }}"
    decision_environment: "{{ __activation_item.decision_environment | default(omit) }}"
    restart_policy:   "{{ __activation_item.restart_policy | default('always') }}"
    is_enabled:       "{{ __activation_item.is_enabled | default('true') }}"
    variables:        "{{ __activation_item.dictionary | default(omit) }}"
    state:            "{{ __activation_item.state | default(eda_state | default('present')) }}"
    eda_host:         "{{ eda_host | default(eda_hostname) }}"
    eda_username:     "{{ eda_username | default(omit) }}"
    eda_password:     "{{ eda_password | default(omit) }}"
    validate_certs:   "{{ eda_validate_certs | default(omit) }}"
    request_timeout:  "{{ eda_request_timeout | default(omit) }}"
  loop: "{{ eda_rulebook_activations }}"
  loop_control:
    loop_var: "__activation_item"
  no_log: "{{ eda_configuration_rulebook_activation_secure_logging }}"
  async: 1000
  poll: 0
  register: __rulebook_activations_job_async
  changed_when: not __rulebook_activations_job_async.changed
  vars:
    ansible_async_dir: '{{ eda_configuration_async_dir }}'

- name: "Create rulebook_activation | Wait for finish the rulebook_activation creation"
  ansible.builtin.async_status:
    jid: "{{ __rulebook_activations_job_async_result_item.ansible_job_id }}"
  register: __rulebook_activations_job_async_result
  until: __rulebook_activations_job_async_result.finished
  retries: "{{ eda_configuration_rulebook_activation_async_retries }}"
  delay: "{{ eda_configuration_rulebook_activation_async_delay }}"
  loop: "{{ __rulebook_activations_job_async.results }}"
  loop_control:
    loop_var: __rulebook_activations_job_async_result_item
  when: __rulebook_activations_job_async_result_item.ansible_job_id is defined
  no_log: "{{ eda_configuration_rulebook_activation_secure_logging }}"
  vars:
    ansible_async_dir: '{{ eda_configuration_async_dir }}'
...
